PREFIX imdb: <http://academy.ontotext.com/imdb/>
PREFIX schema: <http://schema.org/>

SELECT ?title WHERE {
    ?movie a ?type ;
        schema:genre ?genre ;
        schema:name ?title .
    FILTER (CONTAINS(LCASE(?genre), "fantasy"))
    FILTER (?type = imdb:ColorMovie || ?type = imdb:BlackandWhiteMovie)
}