PREFIX imdb: <http://academy.ontotext.com/imdb/>
PREFIX schema: <http://schema.org/>

SELECT ?title ?commentCount WHERE {
    ?movie a ?type ;
        schema:name ?title ;
        schema:countryOfOrigin <http://academy.ontotext.com/imdb/country/USA> ;
        schema:commentCount ?commentCount .
    FILTER (?commentCount > 500)
    FILTER (?type = imdb:ColorMovie || ?type = imdb:BlackandWhiteMovie)
}