PREFIX imdb: <http://academy.ontotext.com/imdb/>
PREFIX schema: <http://schema.org/>

SELECT ?title ?directorName WHERE {
    ?movie a ?type ;
        schema:name ?title ;
        schema:director ?director ;
        schema:actor ?director .
    ?director schema:name ?directorName .
    FILTER (?type = imdb:ColorMovie || ?type = imdb:BlackandWhiteMovie)
}